-- 테이블: DB_COST_DTL
-- 설명: 원가견적 디테일
-- 스키마: FNF.PRCS
-- 최종 수정: 2025-02-04
-- 관련 테이블: DB_COST_MST (마스터)

CREATE OR REPLACE TABLE FNF.PRCS.DB_COST_DTL (
    PRDT_CD VARCHAR(24) NOT NULL COMMENT 'PK :품번',
    BRD_CD VARCHAR(2) COMMENT '브랜드',
    SESN VARCHAR(4) COMMENT '시즌',
    PART_CD VARCHAR(18) COMMENT '파트코드',
    PO_NO VARCHAR(72) NOT NULL COMMENT 'PK : 발주po',
    COST_QUOTATION_NO VARCHAR(72) COMMENT '견적번호',
    QUOTATION_SEQ NUMBER(38,0) COMMENT '견적seq(max)',
    TYPE1 VARCHAR(20) NOT NULL COMMENT 'PK : 타입:G020',
    TYPE1_NM VARCHAR(100) COMMENT '타입명',
    TYPE1_SEQ NUMBER(38,0) NOT NULL COMMENT 'PK : 타입seq',
    TYPE2 VARCHAR(150) NOT NULL COMMENT 'PK : 분류:G021',
    TYPE2_NM VARCHAR(120) COMMENT '분류명',
    TYPE3 VARCHAR(256) COMMENT '상세분류',
    MFAC_COMPY VARCHAR(72) COMMENT '협력사코드',
    MFAC_COMPY_NM VARCHAR(100) COMMENT '협력사명',
    UNIT VARCHAR(32) COMMENT '단위',
    WIDTH VARCHAR(120) COMMENT '폭',
    MFAC_OFFER_CONS FLOAT COMMENT '협력사제시원가_요척',
    MFAC_OFFER_COST FLOAT COMMENT '협력사제시원가_단가',
    MFAC_OFFER_COST_AMT FLOAT COMMENT '벤더제시원가_금액',
    MFAC_OFFER_COST_AMT_CURR FLOAT COMMENT '벤더제시원가_금액_현지통화',
    LOSS FLOAT COMMENT 'loss',
    MFAC_NEGO_CONS FLOAT COMMENT '본사협의단가_요척',
    MFAC_NEGO_COST FLOAT COMMENT '본사협의단가_단가',
    MFAC_NEGO_COST_AMT FLOAT COMMENT '본사협의단가_금액',
    MFAC_NEGO_COST_AMT_CURR FLOAT COMMENT '본사협의단가_금액_현지통화',
    CURRENCY VARCHAR(5) COMMENT '통화',
    EXCHANGE_RATE FLOAT COMMENT '환율',
    PRIMARY KEY (PRDT_CD, PO_NO, TYPE1, TYPE1_SEQ, TYPE2)
)
COMMENT='원가견적 디테일';

-- 참고사항
-- - TYPE1 코드 (G020): 원가 타입 구분
-- - TYPE2 코드 (G021): 원가 분류 구분
-- - MST와 JOIN: PRDT_CD + PO_NO로 연결
-- - 협력사제시원가 vs 본사협의단가: 견적 협상 과정 추적
