-- 테이블: DB_COST_MST
-- 설명: 원가견적 마스터
-- 스키마: FNF.PRCS
-- 최종 수정: 2025-02-04

CREATE OR REPLACE TABLE FNF.PRCS.DB_COST_MST (
    PRDT_CD VARCHAR(24) NOT NULL COMMENT 'PK : 품번',
    BRD_CD VARCHAR(2) COMMENT '브랜드',
    SESN VARCHAR(4) COMMENT '시즌',
    PART_CD VARCHAR(18) COMMENT '품번',
    PO_NO VARCHAR(72) NOT NULL COMMENT 'PK : 발주no',
    COST_QUOTATION_NO VARCHAR(72) COMMENT '견적번호',
    QUOTATION_SEQ NUMBER(38,0) COMMENT 'PK :견적seq(max 값 으로 사용)',
    QTY NUMBER(38,0) COMMENT '수량',
    ORIGIN VARCHAR(5) COMMENT '원산지',
    QUOTATION_STAT_CD VARCHAR(4) COMMENT '진행상태코드: G018',
    QUOTATION_STAT_NM VARCHAR(100) COMMENT '진행상태',
    QUOTATION_APV_STAT_CD VARCHAR(72) COMMENT '결재상태코드: G019',
    QUOTATION_APV_STAT_NM VARCHAR(100) COMMENT '결재상태',
    MFAC_COMPY VARCHAR(72) COMMENT 'PK : 협력사 코드',
    MFAC_COMPY_NM VARCHAR(100) COMMENT '협력사명',
    MFAC_OPINION VARCHAR(600) COMMENT '협력사 의견',
    COST_QUOTATION_ID VARCHAR(100) COMMENT '견적서id (FK) (23S~)',
    QUOTATION_REQ_DT DATE COMMENT '견적요청일자',
    QUOTATION_SUBMIT_DT DATE COMMENT '견적제출일자',
    MFAC_OFFER_COST_AMT FLOAT COMMENT '견적금액',
    MFAC_NEGO_COST_AMT FLOAT COMMENT '검토금액',
    MFAC_OFFER_COST_CURRENCY FLOAT COMMENT '견적단가(통화)',
    MFAC_OFFER_COST NUMBER(38,0) COMMENT '견적단가(원화)',
    TAG_AMT NUMBER(38,0) COMMENT '판매가(KRW)',
    HQ_SUPPLY_AMT NUMBER(38,0) COMMENT '본사공급자재단가',
    EXTRA_AMT NUMBER(38,0) COMMENT '부대비용',
    MFAC_COST_AMT NUMBER(38,0) COMMENT '예상제조원가',
    MARKUP FLOAT COMMENT '예상 마크업',
    EXCHAGE_RATE FLOAT COMMENT '환율',
    EXCHAGE_RATE_CONFIRM_DT DATE COMMENT '환율 승인일',
    CN_SOURCING_AGENCY_YN BOOLEAN COMMENT '소싱대행여부(중국)',
    CN_SOURCING_AGENCY_COST FLOAT COMMENT '소싱대행단가(중국)',
    CN_EXCHAGE_RATE FLOAT COMMENT '중국 환율'
)
COMMENT='원가견적 마스터';

-- PK 구성: PRDT_CD + PO_NO + QUOTATION_SEQ + MFAC_COMPY

-- 참고사항
-- - 진행상태코드 (G018): 견적 진행 상태 관리
-- - 결재상태코드 (G019): 결재 프로세스 상태 관리
-- - COST_QUOTATION_ID: 23S 시즌부터 사용되는 견적서 FK
